# ============================================================
# Clinician UI — CAD Sperm Analysis System
# Gọi FastAPI endpoints: /predict, /explain, /report
#
# Cách chạy:
#   1. Chạy FastAPI trước:  uvicorn app:app --reload
#   2. Chạy Streamlit:      streamlit run streamlit_app.py
# ============================================================
# pip install streamlit requests

import base64
import requests
import streamlit as st
from PIL import Image
import io

# ── Config ──────────────────────────────────────────────────
API_BASE = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="CAD Sperm Analysis",
    layout="wide",
)

# ── Header ───────────────────────────────────────────────────
st.title("CAD Sperm Analysis System")
st.caption("Computer-Aided Diagnostic · ResNet50 + EfficientNet-B0 · ONNX Runtime")
st.divider()

# ── Sidebar ───────────────────────────────────────────────────
with st.sidebar:
    st.header("Settings")
    show_gradcam = st.toggle("Show Grad-CAM heatmaps", value=True)
    show_report  = st.toggle("Generate clinical report (Claude API)", value=True)
    st.divider()
    st.caption("FastAPI server: " + API_BASE)

    # Health check
    try:
        health = requests.get(f"{API_BASE}/health", timeout=3).json()
        st.success("Server online")
        st.json(health)
    except Exception:
        st.error("Server offline — chạy `uvicorn app:app --reload` trước")

# ── Upload ────────────────────────────────────────────────────
uploaded = st.file_uploader(
    "Upload microscopy image (PNG / JPG / BMP)",
    type=["png", "jpg", "jpeg", "bmp"],
)

if uploaded is None:
    st.info("Upload ảnh để bắt đầu phân tích")
    st.stop()

# Hiển thị ảnh gốc
col_img, col_result = st.columns([1, 2])
with col_img:
    st.subheader("Input Image")
    st.image(uploaded, use_column_width=True)

img_bytes = uploaded.read()

# ── Gọi /predict ─────────────────────────────────────────────
with st.spinner("Running ONNX inference..."):
    try:
        res_predict = requests.post(
            f"{API_BASE}/predict",
            files={"file": (uploaded.name, img_bytes, uploaded.type)},
            timeout=30,
        )
        res_predict.raise_for_status()
        pred = res_predict.json()
    except Exception as e:
        st.error(f"/predict failed: {e}")
        st.stop()

# ── Hiển thị kết quả predict ─────────────────────────────────
with col_result:
    st.subheader("Classification Results")

    c1, c2, c3 = st.columns(3)
    with c1:
        label_color = "🟢" if pred["binary_label"] == "Sperm" else "🔴"
        st.metric("Task A — Binary", f"{label_color} {pred['binary_label']}")
        st.caption(f"Confidence: {pred['binary_conf']:.1%}")

    with c2:
        if pred.get("halo_label") and pred["halo_label"] != "N/A":
            st.metric("Task B — Halo", pred["halo_label"])
            st.caption(f"Confidence: {pred.get('halo_conf', 0):.1%}")
        else:
            st.metric("Task B — Halo", "N/A")
            st.caption("Not applicable (non-sperm)")

    with c3:
        st.metric("Inference Latency", f"{pred['latency_ms']:.1f} ms")
        st.caption(pred.get("backend", "ONNX Runtime"))

st.divider()

# ── Grad-CAM ─────────────────────────────────────────────────
if show_gradcam:
    st.subheader("Grad-CAM Explainability")

    with st.spinner("Generating Grad-CAM heatmaps (PyTorch)..."):
        try:
            res_explain = requests.post(
                f"{API_BASE}/explain",
                files={"file": (uploaded.name, img_bytes, uploaded.type)},
                timeout=60,
            )
            res_explain.raise_for_status()
            explain = res_explain.json()

            gc1, gc2 = st.columns(2)
            with gc1:
                st.caption("Task A — Binary Detection (ResNet50 · layer4[-1])")
                img_a = Image.open(io.BytesIO(base64.b64decode(explain["gradcam_task_a"])))
                st.image(img_a, use_column_width=True)

            with gc2:
                st.caption("Task B — Halo Morphology (EfficientNet-B0 · features[-1])")
                img_b = Image.open(io.BytesIO(base64.b64decode(explain["gradcam_task_b"])))
                st.image(img_b, use_column_width=True)

            st.caption(
                "🔴 Red/yellow regions = high activation (model focuses here) · "
                "🔵 Blue = low activation"
            )

        except Exception as e:
            st.warning(f"Grad-CAM unavailable: {e}")

    st.divider()

# ── Clinical Report (Claude API) ─────────────────────────────
if show_report:
    st.subheader("Clinical Report")
    st.caption("Generated by Claude API · For screening support only, not a definitive diagnosis")

    with st.spinner("Generating clinical summary (Claude API)..."):
        try:
            res_report = requests.post(
                f"{API_BASE}/report",
                files={"file": (uploaded.name, img_bytes, uploaded.type)},
                timeout=60,
            )
            res_report.raise_for_status()
            report = res_report.json()

            # Hiển thị report
            st.info(report["clinical_summary"])

            # Metadata
            with st.expander("Report metadata"):
                st.json({
                    "llm_model":      report.get("llm_model"),
                    "llm_latency_ms": report.get("llm_latency_ms"),
                    "inference_ms":   report.get("inference_ms"),
                })

        except Exception as e:
            st.warning(f"Clinical report unavailable: {e}")
            st.caption("Check ANTHROPIC_API_KEY environment variable")

    st.divider()

# ── Footer ────────────────────────────────────────────────────
st.caption(
    "**Disclaimer**: This system is intended for research and educational purposes only. "
    "Results should not be used as the sole basis for clinical decisions."
)
